title: 老杨的博客
description: 记录我的技术人生
baseurl: "/"
url: "https://blog.ygqygq2.com"
plugins:
  - jekyll-paginate
markdown: kramdown
highlighter: rouge

paginate: 10
paginate_path: "/page:num/"

github_username: ygqygq2
short_url: ''
disqus: username

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag

production_url:  https://blog.ygqygq2.com/
source_url:  https://github.com/ygqygq2/blog/
